### ISSUE TITLE
Remove HTML from responses

### ISSUE THREAD

**Issue by AmadeusW** [KirillOsenkov/QuickInfo#13]
The readme mentions getting quick answers from command line as motivation for this project
> how do I generate a random Guid from command line

Currently, queries return HTML that is then directly placed in the website.
Would you be open to accepting a PR that refactors all queries to internally work with data structures friendly for programmatic consumption? Ultimately, the `Engine` could format these response as HTML, **plain text** or whatever is the flavor of the month.

How would you like these data structure to look like? How about a collection key-value pairs?

**Comment by KirillOsenkov** [comment]
Yeah I've been wanting to do a refactoring to extract a library and separate it from HTML, so it could be used on mobile. And have translation layers that would render HTML, Json etc. like you say.

The data structure has to be semantic, I didn't think much about it yet, but I think POCO would work best. I was thinking of having a set of primitives, such as `Group`, `List`, `Tuple`, `Plain text`, `Table`, `KeyValuePair`, so you could compose them. And each primitive could have a `PropertyBag` of custom annotations. You could have a `Color swatch` or `Unicode glyph sample` annotation I guess. Maybe similar to what Christian did for the new Quick Info API. To tell the renderer that the plain text should be interpreted as a color by the renderer. For each content returned by the engine we should shoehorn it into these data structures, and try to keep these data structures minimal and orthogonal. 

And all HTML logic should be in a parallel set of renderers (HtmlRenderer) that "visits" the data structure and knows how to render its primitives. And it would be up to the renderer to provide "stylesheets" for colors, etc. 

One could then imagine also exposing web services that return "raw" data instead of Html so you could have programmatic access. 

It all depends on how passionate you are about this. If you need this and really want to write the PR, go ahead and give it a shot ;) Otherwise I might get to it soonish.

**Comment by KirillOsenkov** [comment]
The refactoring is now done, now to implement the console client.

**Comment by KirillOsenkov** [comment]
And I am thinking of using this for Console output: https://github.com/Athari/CsConsoleFormat

**Comment by KirillOsenkov** [comment]
This is now implemented, let me know what you think!

**Comment by AmadeusW** [comment]
That's a cool project CsConsoleFormat.
There is still no way to output raw text from the web server, though? I guess it's good enough to have info available locally, the downside is that you need to keep updating it to get new quick infos

**Comment by KirillOsenkov** [comment]
Ah, makes sense. Filed this issue:
https://github.com/KirillOsenkov/QuickInfo/issues/22
